### ISSUE TITLE
OOM-kill for large simualtions on ARCHER2

### ISSUE THREAD

**Issue by keithbennett** [Warwick-Plasma/epoch#118] opened 2021-02-12 12:24 UTC
In GitLab by Oscar Jakobsson on 23 Jan 2021, 18:10 UTC (GitLab issue GL#2302)

Dear developers, 
Running singe/few node simulations on archer2 seems to work just fine with EPOCH (V. 4.17.13, COMPILER=archer, default archer2 modules).
With jobs that required 100 nodes, 2400 cores, on archer I now run into memory issues on archer2.
I have a attached a minimal working input deck and jobscript which demonstrates these issues. When run on:
- 20 nodes and --tasks-per-node=128 the simulation stops by oom-kill after 7 sdf are written:
slurmstepd: error: Detected 1 oom-kill event(s) in step 74331.0 cgroup. Some of your processes may have been killed by the cgroup out-of-memory handler.
mlx5: nid001058: got completion with error:
00000000 00000000 00000000 00000000
00000000 00000000 00000000 00000000
00000005 00000000 00000000 00000000
00000000 00008a12 0a00db18 1ff7a2d3
srun: error: nid001076: tasks 1536,1663: Out Of Memory

- 20 nodes and --tasks-per-node=64 the simulation stops by oom-kill after 14 output files, presumably because the cores now have more memory available. 

- 40+ nodes gives a new error:
lib-4205 : UNRECOVERABLE library error 
  The program was unable to request more memory space.

Given that each core on archer2 has less memory than on archer I expect that more cores will be needed for the same simulation. So far I am stuck here though. 

Any help is much appreciated.

Thanks, 
Oscar

[input.deck](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/92e02a7e4d8aac4c1cbeacc54f28567d/input.deck)

[errors_20nodes.dat](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/17e69720245d77162231ac5df6c1a702/errors_20nodes.dat)

[errors_40nodes.dat](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/860de23b9cf89da8b0a1e29fc5d1b56d/errors_40nodes.dat)

[jobscript.slurm](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/f7ff1502be617f36f0eb0d54f5405f88/jobscript.slurm)

[ModuleList.txt](../blob/37c47bd3c9805e46ecfa4681221ec19dd3629922/uploads/29cac7ae06d73a26f3362008a648f226/ModuleList.txt)

**Comment by TomGoffrey** [comment] 2021-02-13 12:28
I've notified affected users already, but in case others are having this issue, as far as I can tell this is caused by a "known issue" with ARCHER2, rather than a problem with EPOCH. The issue is documented at:

https://docs.archer2.ac.uk/known-issues/#memory-leak-leads-to-job-fail-by-out-of-memory-oom-error

Following the advice on that page, I have successfully avoided OOM errors by removing the following line from my submission script:

```
module load epcc-job-env
```

and adding the following lines:

```
module restore /etc/cray-pe.d/PrgEnv-cray
module switch cray-mpich/8.0.16 cray-mpich-ucx/8.0.16
module switch craype-network-ofi craype-network-ucx
```

The exact lines you need to add will depend on the environment you used to compile EPOCH.

**Comment by TomGoffrey** [comment] 2021-03-05 10:31
Closing this. Users have confirmed the above workaround fixes the problem.

Issue with ARCHER2, not EPOCH.

**Closed by TomGoffrey** 2021-03-05 10:31 UTC
